title: "Iglesias Vázquez, Félix — Research Profile"
email: "felix.iglesias@tuwien.ac.at"
description: "TU Wien"
baseurl: "/research"  # porque tu sitio está en /research
url: "https://felixig.github.io"
author:
  name: "FIV"

theme: minima
permalink: pretty
exclude:
  - "README.md"
  - "LICENSE.md"
  - "changelog.md"
  - ".github"
  - "scripts"

markdown: kramdown
highlighter: rouge
